### ISSUE TITLE
TSSEnrichment giving Nan

### ISSUE THREAD

**Issue by rojinsafavi** [timoast/signac#127]
I am not sure why I get NaN for the TSS.enrichment?

```dim(atac)```
```114010 44420```

```
# to save time use the first 2000 TSSs
atac <- TSSEnrichment(object = atac, tss.positions = tss.ranges[1:2000])
```

```
Finding + strand cut sites

Finding - strand cut sites

Computing mean insertion frequency in flanking regions

Normalizing TSS score

```
`atac$TSS.enrichment`

gives NaN

**Comment by timoast** [comment]
All the values are NaN or only some of them? Can you provide the full code you're using and the output of `sessionInfo()`?

**Comment by rojinsafavi** [comment]
Thanks for the quick response.
They're all NaN

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /projects/sysbio/projects/rojin/anaconda3/envs/heart_env/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  IRdisplay_0.7.0 pbdZMQ_0.3-3    tools_3.6.1    
 [5] htmltools_0.4.0 pillar_1.4.3    base64enc_0.1-3 crayon_1.3.4   
 [9] Rcpp_1.0.4      uuid_0.1-2      IRkernel_1.1    jsonlite_1.6.1 
[13] digest_0.6.25   repr_1.1.0      rlang_0.4.5     evaluate_0.14  
```

**Comment by timoast** [comment]
Can you provide the full code you're using?

**Comment by timoast** [comment]
Also, this session info does not show Signac loaded. Can you provide the session info from the R session that you ran `TSSEnrichment`?

**Comment by rojinsafavi** [comment]
My apologies, I sent you the sessionInfo before loading the libraries. I will post the full code shortly

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /projects/sysbio/projects/rojin/anaconda3/envs/env/lib/R/lib/libRblas.so

locale:
[1] en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] EnsDb.Hsapiens.v86_2.99.0 ensembldb_2.10.2         
 [3] AnnotationFilter_1.10.0   GenomicFeatures_1.38.2   
 [5] AnnotationDbi_1.48.0      Biobase_2.46.0           
 [7] patchwork_1.0.0           ggplot2_3.3.0            
 [9] Seurat_3.1.1              Signac_0.2.4             
[11] GenomicRanges_1.38.0      GenomeInfoDb_1.22.0      
[13] IRanges_2.20.2            S4Vectors_0.24.3         
[15] BiocGenerics_0.32.0      

loaded via a namespace (and not attached):
  [1] uuid_0.1-2                  BiocFileCache_1.10.2       
  [3] sn_1.5-5                    plyr_1.8.6                 
  [5] igraph_1.2.4.2              repr_1.1.0                 
  [7] lazyeval_0.2.2              splines_3.6.1              
  [9] BiocParallel_1.20.1         listenv_0.8.0              
 [11] TH.data_1.0-10              digest_0.6.25              
 [13] htmltools_0.4.0             gdata_2.18.0               
 [15] magrittr_1.5                memoise_1.1.0              
 [17] BSgenome_1.54.0             cluster_2.1.0              
 [19] ROCR_1.0-7                  ggfittext_0.8.1            
 [21] globals_0.12.5              Biostrings_2.54.0          
 [23] RcppParallel_5.0.0          matrixStats_0.56.0         
 [25] R.utils_2.9.2               sandwich_2.5-1             
 [27] askpass_1.1                 prettyunits_1.1.1          
 [29] colorspace_1.4-1            blob_1.2.1                 
 [31] rappdirs_0.3.1              ggrepel_0.8.2              
 [33] dplyr_0.8.5                 crayon_1.3.4               
 [35] RCurl_1.98-1.1              jsonlite_1.6.1             
 [37] survival_3.1-11             zoo_1.8-7                  
 [39] ape_5.3                     glue_1.3.2                 
 [41] gtable_0.3.0                zlibbioc_1.32.0            
 [43] XVector_0.26.0              leiden_0.3.3               
 [45] DelayedArray_0.12.2         future.apply_1.4.0         
 [47] scales_1.1.0                mvtnorm_1.1-0              
 [49] DBI_1.1.0                   bibtex_0.4.2.2             
 [51] Rcpp_1.0.4                  metap_1.3                  
 [53] plotrix_3.7-7               viridisLite_0.3.0          
 [55] progress_1.2.2              reticulate_1.14            
 [57] rsvd_1.0.3                  bit_1.1-15.2               
 [59] SDMTools_1.1-221.2          tsne_0.1-3                 
 [61] htmlwidgets_1.5.1           httr_1.4.1                 
 [63] gplots_3.0.3                RColorBrewer_1.1-2         
 [65] ellipsis_0.3.0              TFisher_0.2.0              
 [67] ica_1.0-2                   farver_2.0.3               
 [69] pkgconfig_2.0.3             XML_3.99-0.3               
 [71] R.methodsS3_1.8.0           ggseqlogo_0.1              
 [73] uwot_0.1.5                  dbplyr_1.4.2               
 [75] labeling_0.3                reshape2_1.4.3             
 [77] tidyselect_1.0.0            rlang_0.4.5                
 [79] munsell_0.5.0               tools_3.6.1                
 [81] RSQLite_2.2.0               ggridges_0.5.2             
 [83] evaluate_0.14               stringr_1.4.0              
 [85] npsurv_0.4-0                bit64_0.9-7                
 [87] fitdistrplus_1.0-14         caTools_1.18.0             
 [89] purrr_0.3.3                 RANN_2.6.1                 
 [91] pbapply_1.4-2               future_1.16.0              
 [93] nlme_3.1-145                R.oo_1.23.0                
 [95] biomaRt_2.42.0              hdf5r_1.3.1                
 [97] compiler_3.6.1              png_0.1-7                  
 [99] plotly_4.9.2                curl_4.3                   
[101] lsei_1.2-0                  tibble_2.1.3               
[103] stringi_1.4.6               RSpectra_0.16-0            
[105] lattice_0.20-40             IRdisplay_0.7.0            
[107] ProtGenerics_1.18.0         Matrix_1.2-18              
[109] multtest_2.42.0             vctrs_0.2.4                
[111] mutoss_0.1-12               pillar_1.4.3               
[113] lifecycle_0.2.0             BiocManager_1.30.10        
[115] Rdpack_0.11-1               lmtest_0.9-37              
[117] RcppAnnoy_0.0.16            data.table_1.12.8          
[119] cowplot_1.0.0               bitops_1.0-6               
[121] irlba_2.3.3                 gbRd_0.4-11                
[123] gggenes_0.4.0               rtracklayer_1.46.0         
[125] R6_2.4.1                    gridExtra_2.3              
[127] KernSmooth_2.23-15          codetools_0.2-16           
[129] MASS_7.3-51.5               gtools_3.8.1               
[131] assertthat_0.2.1            SummarizedExperiment_1.16.1
[133] openssl_1.4.1               withr_2.1.2                
[135] sctransform_0.2.1           GenomicAlignments_1.22.1   
[137] Rsamtools_2.2.3             mnormt_1.5-6               
[139] multcomp_1.4-12             GenomeInfoDbData_1.2.2     
[141] hms_0.5.3                   grid_3.6.1                 
[143] IRkernel_1.1                tidyr_1.0.2                
[145] Rtsne_0.15                  pbdZMQ_0.3-3               
[147] numDeriv_2016.8-1.1         base64enc_0.1-3  
```

**Comment by timoast** [comment]
@rojinsafavi any update on this?

**Comment by rojinsafavi** [comment]
Yes, I was trying a couple of things but still had the error. I'm posting the code I use. I have 5 files, and I first follow our merging tutorial to merge them. the final output looks like this:



```
An object of class Seurat 
550587 features across 44420 samples within 2 assays 
Active assay: peaks (114010 features)
 1 other assay present: ATAC
 2 dimensional reductions calculated: lsi, umap
```

library(Signac)
library(Seurat)
library(GenomeInfoDb)
library(ggplot2)
library(patchwork)
set.seed(1234)

library("EnsDb.Hsapiens.v86")

atac$pct_reads_in_peaks <- atac$peak_region_fragments / atac$passed_filters * 100
atac$blacklist_ratio <- atac$blacklist_region_fragments / atac$peak_region_fragments

VlnPlot(
  object = atac,
  features = c('pct_reads_in_peaks', 'blacklist_ratio', 
               'nucleosome_signal', 'peak_region_fragments'),
  pt.size = 0.1,
  ncol = 4, dims = c(10, 6)) + NoLegend()

![image](https://user-images.githubusercontent.com/19545198/79020935-12f5cf00-7b2f-11ea-97eb-c4d13f14e0a3.png)


# create granges object with TSS positions
gene.ranges <- genes(EnsDb.Hsapiens.v86)
gene.ranges <- gene.ranges[gene.ranges$gene_biotype == 'protein_coding', ]


head(as.data.frame(gene.ranges))


  | seqnames | start | end | width | strand | gene_id | gene_name | gene_biotype | seq_coord_system | symbol | entrezid
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

1 | 69091 | 70008 | 918 | + | ENSG00000186092 | OR4F5 | protein_coding | chromosome | OR4F5 | 79501
1 | 182393 | 184158 | 1766 | + | ENSG00000279928 | FO538757.2 | protein_coding | chromosome | FO538757.2 | 10798407....
1 | 184923 | 200322 | 15400 | - | ENSG00000279457 | FO538757.1 | protein_coding | chromosome | FO538757.1 | NA
1 | 450740 | 451678 | 939 | - | ENSG00000278566 | OR4F29 | protein_coding | chromosome | OR4F29 | 729759, ....
1 | 685716 | 686654 | 939 | - | ENSG00000273547 | OR4F16 | protein_coding | chromosome | OR4F16 | 81399, 26683
1 | 923928 | 944581 | 20654 | + | ENSG00000187634 | SAMD11 | protein_coding | chromosome | SAMD11 | 148398


tss.ranges <- GRanges(
  seqnames = seqnames(gene.ranges),
  ranges = IRanges(start = start(gene.ranges), width = 2),
  strand = strand(gene.ranges)
)

head(as.data.frame(tss.ranges))

seqlevelsStyle(tss.ranges) <- 'UCSC'
tss.ranges <- keepStandardChromosomes(tss.ranges, pruning.mode = 'coarse')

head(as.data.frame(tss.ranges))

	seqnames	start	end	width	strand
<fct>	<int>	<int>	<int>	<fct>
1	chr1	69091	69092	2	+
2	chr1	182393	182394	2	+
3	chr1	184923	184924	2	-
4	chr1	450740	450741	2	-
5	chr1	685716	685717	2	-
6	chr1	923928	923929	2	+


Now here is problem:
# to save time use the first 2000 TSSs
atac <- TSSEnrichment(object = atac, tss.positions = tss.ranges[1:2000])

atac$TSS.enrichment

IVS_AAACGAAAGAGAGGTA-1<NA>IVS_AAACGAAAGATCTCAC-1<NA>IVS_AAACGAAAGCAGGACT-1<NA>IVS_AAACGAAAGGTTCGAG-1<NA>IVS_AAACGAAAGTACAGTA-1<NA>IVS_AAACGAAAGTCGAGCA-1<NA>IVS_AAACGAACAAGGCGTA-1<NA>IVS_AAACGAACAAGTCTCA-1<NA>

atac$TSS_fragments
IVS_AAACGAAAGAGAGGTA-11524IVS_AAACGAAAGATCTCAC-11921IVS_AAACGAAAGCAGGACT-11113IVS_AAACGAAAGGTTCGAG-11954IVS_AAACGAAAGTACAGTA-11776IVS_AAACGAAAGTCGAGCA-16206IVS_AAACGAACAAGGCGTA-

**Comment by timoast** [comment]
I just pushed some changes to the develop branch that might fix this, can you install from develop and try again?

Also, this doesn't look like your full code, it doesn't show how the object `atac` was created.

**Comment by rojinsafavi** [comment]
I will give it a try now. Thank you.

I will post how I generated atac object soon, I followed one of your tutorials.

Thanks again,
Rojin

**Comment by timoast** [comment]
Any update on this?

**Comment by rojinsafavi** [comment]
So I downloaded the github version. But I am still having the same problem. I also forgot to mention that I get an error at this step too (Since I was getting an error I skept it):

```
heart
An object of class Seurat 
550587 features across 44420 samples within 2 assays 
Active assay: peaks (114010 features)
 1 other assay present: ATAC
 2 dimensional reductions calculated: lsi, umap


heart <- NucleosomeSignal(object = heart)
Extracting reads in requested region

Computing ratio of mononucleosomal to nucleosome-free fragments

Error in `[.data.table`(fragments.use, , c("cell", "length")): column(s) not found: length
Traceback:

1. NucleosomeSignal(object = heart)
2. as.data.frame(x = fragments.use[, c("cell", "length")])
3. fragments.use[, c("cell", "length")]
4. `[.data.table`(fragments.use, , c("cell", "length"))
5. stop("column(s) not found: ", paste(ansvars[is.na(ansvals)], 
 .     collapse = ", "))

```

When I skip the nucleosome part, I get the same NaN output as before

You also asked how I generated fragments and atac files, I exactly followed your tutorial, and I got no error.

**Comment by timoast** [comment]
That error in `NucleosomeSignal` is probably due to not finding any fragments with a cell barcode matching the barcode in the object. Did you update the cell barcode names in the fragment file to match the cell names in the object when you did the merge?

**Comment by rojinsafavi** [comment]
I did not do that, may I ask how I should do that?

**Comment by timoast** [comment]
It's explained in the merge vignette: https://satijalab.org/signac/articles/merging.html#merge-fragment-files-1

**Comment by rojinsafavi** [comment]
I see. I believe I did that but I am gonna re-do the fragment part and let you know if I still get the error.

Thank you very much

**Comment by timoast** [comment]
If you look at the fragment file (for example, running `gzip -d fragments.tsv.gz | head`) you should be able to see if a cell prefix has been added to the cell names that matches the cell prefix in the merged Seurat object

**Comment by rojinsafavi** [comment]
It seems to be working now! thanks for the advice
