### ISSUE TITLE
GeneActivity() duplicates genes on pseudoautosomal regions of XY chromosomes

### ISSUE THREAD

**Issue by danielcgingerich** [timoast/signac#521]
My goal is to create a gene activity matrix that perfectly aligns with the features of a scRNA seurat object.  All data, ATAC and RNA, was mapped to GRCh38p13.  As you know, duplicate gene names are given a decimal point suffix in seurat objects.  To deal with this, I manually added these suffixes to my gene annotations:
 See: 
```
rna <- readRDS('rna99.rds')
atac <- readRDS(atac99.rds'))

hg38 <- rtracklayer::import(hg38.path)
genome(hg38) <- "hg38"
seqlevelsStyle(hg38) <- "UCSC"

#make all genes 'protein coding' so they are included in gene activities
hg38$gene_biotype <- "protein_coding"
```

Since Seurat adds decimal points to duplicate genes, need to do the same for annotations so that gene activity matrix aligns with scRNA Seurat object

```
#features.tsv is the 10X cellranger output with gene names and ensembl ID's
features.tsv <- read.table('features.tsv')

#filter out genes not present in scRNA data. 
hg38 <- hg38[hg38$gene_id %in% features.tsv$ensg,]

#use ensg IDs to identify which duplicate gene has added suffix in the scRNA Seurat objects
#rename genes in the annotation according to RNA object names
df <- data.frame("rownames"=rownames(rna), "feature"=features.tsv$gene_name, "ensg" = features.tsv$ensg)
df2 <- df[df[,1] != df[,2],]
for (i in 1:nrow(df2)){
  hg38$gene_name[which(hg38$gene_id == df2[i,3])] <- df2[i,1]
}

Annotation(atac) <- hg38

mtx <- GeneActivity(atac)
```

As you can see, hg38 has all the same genes as RNA Seurat objects, with the same names and added decimal points: 

```
nrow(rna)
36601
length(unique(hg38$gene_name))
36601
table(hg38$gene_name %in% rownames(rna))
TRUE
2767648
```

The gene activity matrix is still not aligning

```
nrow(mtx)
36588
length(unique(rownames(mtx))
36559
```

It makes sense that there are 36601-13 = 36588 rows (mitochondrial genes excluded from gene activity matrix).
However, you can see that there are duplicates in the matrix, even after I manually changed the gene names

**Which means the gene activity matrix is duplicating some genes and leaving out others, even after I made sure all genes in the annotations were unique. ** 

Most of the left out genes come from unlocalized contiguous sequences, like KI270721.1.
Reads from these sequences are not present in my 10X cellranger data, so I am not worried about them.  

I am concerned about why there are duplicate genes in my gene activity matrix even after I manually changed the gene names for each duplicate in the annotations: 

```
rownames(mtx)[duplicated(rownames(mtx))]
 [1] "PLCXD1"     "GTPBP6"     "LINC00685"  "PPP2R3B"    "AL732314.6"
 [6] "AL732314.4" "SHOX"       "AL672277.1" "CRLF2"      "CSF2RA"
[11] "IL3RA"      "SLC25A6"    "LINC00106"  "ASMTL-AS1"  "ASMTL"
[16] "P2RY8"      "AKAP17A"    "ASMT"       "AL683807.1" "AL683807.2"
[21] "DHRSX"      "DHRSX-IT1"  "ZBED1"      "LINC00102"  "CD99"
[26] "SPRY3"      "VAMP7"      "IL9R"       "WASIR1"
```

Upon inspection of these genes, each one maps to both the X and the Y chromosome.  Even though X and Y are homologous, the computer treats them as separate sets, and thus will add a suffix to the end of them.  Is there a way to work around this?

**Comment by danielcgingerich** [comment]
Another major issue with the pseudoautosomal regions: 

I noticed in the gene activity matrix, there are 4 genes "SPRY3", "VAMP7", "IL9R", "WASIR1" which have unusually high fragment counts (in the hundreds).  Not only this, but within a cell, all 4 genes have similar number of counts: 

```
mtx <- atac@assays$gene.activity@counts
mtx[c('SPRY3', 'VAMP7', 'IL9R'),]
SPRY3   1232 111 22 39 349 132 59 856 67 387 42 1804 90 404 28 493 1070  
VAMP7 1233 111 22 39 349 132 59 856 67 388 42 1801 90 404 28 494 1072 
IL9R      1233 111 22 39 349 132 59 856 67 391 42 1800 89 403 28 494 1080 
```

After looking at the source code, this appears to be a problem with CollapseToLongestTranscript.  The function takes the min(start) and max(end) from both X and Y chromosomes.  The result is absolutely huge, overlapping genomic ranges (see below).  In the GRanges object below, notice the numeric coordinates for the X and Y chromosomes are the same for each pseudoautosomal gene:
```
annotation <- Annotation(atac)
transcripts <- CollapseToLongestTranscript(annotation)
transcripts[transcripts$gene_name %in% c('SPRY3', 'VAMP7', 'IL9R'),]
GRanges object with 6 ranges and 2 metadata columns:
      seqnames             ranges strand |   gene_name   gene_biotype
         <Rle>          <IRanges>  <Rle> | <character>    <character>
  [1]     chrX 56954332-155782459      + |       SPRY3 protein_coding
  [2]     chrY 56954332-155782459      + |       SPRY3 protein_coding       #same numeric coordinates as previous row
  [3]     chrX 57067865-155943769      + |       VAMP7 protein_coding
  [4]     chrY 57067865-155943769      + |       VAMP7 protein_coding     #same numeric coordinates as previous row
  [5]     chrX 57184101-156010817      + |        IL9R protein_coding
  [6]     chrY 57184101-156010817      + |        IL9R protein_coding  #same numeric coordinates as previous row
  -------
  seqinfo: 47 sequences from an unspecified genome; no seqlengths

```
Width of the first range: 155782459-56954332 =  98828127... woah
No wonder the fragment counts are so high and all similar! haha

So how can I fix this?

**Comment by timoast** [comment]
Hi @danielcgingerich, thanks for finding this bug! I think this was due to some distinct genes having the same name (gotta love gene naming...), and since we were collapsing based on name, we got some weird coordinates for those genes. This should be fixed now on the develop branch by instead collapsing on the gene ID. Can you try installing from the develop branch and see if you still have the same issue?

**Comment by danielcgingerich** [comment]
@timoast Thanks for fixing this issue!  Yes, gene nomenclature drives me up the wall sometimes haha.  I think this fix is very useful for duplicate gene names across different sets of homologous chromosomes.  However, it looks like the genes in pseudoautosomal regions still have the same ensembl gene ID number, which I can foresee this being a problem.  Gencode adds the suffix "_PAR" to ensembl gene ID numbers on the Y chromosome, so this fix should work for the reference genome I am using.  If I am correct, the references used in the vignettes do not include Y chromosome PARs, so it shouldnt be a problem with those references either.  Also, I looked at my cellranger count data, and there appears to be no Y chromosome counts in the PAR ranges.  It seems as though cellranger atac maps all PAR fragments to the X chromosome.  Perhaps simply removing the Y chromosome PAR genes from the reference would be a sufficient fix as well?

**Comment by timoast** [comment]
Right, the Y chromosome versions are not included in the Ensembl annotation, and in Gencode they add `_PAR` which also makes them unique. I also tested with the Gencode hg38 annotation and the problem seems to be solved. 

> Perhaps in addition to collapsing based on ensembl ID, you need to also remove the Y chromosome PAR regions from the reference?

I don't think this should be necessary, it's possible that people would have data mapped to chrY PAR so we should keep the ability to retain that annotation
